"use client";

import { useMemo, useState, type FormEvent, type ReactNode } from "react";

type Tone = "ok" | "watch" | "alert" | "critical" | "info";
type Stage = { label: string; time: string; note: string; tone: Tone };
type Props = {
  subview: string; horizon: string; profile: string; scenarioStep: number; stage: Stage;
  mapStatus: string; layers: Record<string, boolean>; selectedAsset: string;
  renderMap: () => ReactNode; onHorizon: (value: string) => void;
  onToggleLayer: (key: string) => void; onSelectAsset: (value: string) => void;
  onAgents: () => void; onToast: (message: string) => void; onTower: () => void;
  onClimate: () => void; onHazards: () => void; onTwin: () => void;
  onChain: () => void; onRisk: () => void;
};

export const planningTabs = [
  "Situação do Plano", "Plano Integrado 72H", "Cenários", "Alternativas & Decisão",
  "Otimização", "Produção & Estoques", "Logística & Porto", "Manutenção & Recursos",
  "Ambiental & Adaptação", "Plano Aprovado", "Aderência & Replan",
  "Histórico & Versões", "Agentes & Integrações", "Relatórios",
];

export const planningScenarioStages: Stage[] = [
  ["Baseline","T+00","PLN-v18 · C17 96% · MV Atlas 21:00","ok"],
  ["ChainSignal","T+10","CHS-0184 · 12,4 kt em risco","critical"],
  ["Cenário","T+12","SCN-0184 criado","info"],
  ["6 alternativas","T+14","Action Catalog aplicado","info"],
  ["Factibilidade","T+16","2 alternativas inviáveis","watch"],
  ["Simulação","T+20","M3 · M4 · M5 sincronizados","info"],
  ["Otimização","T+25","4 alternativas no Pareto","info"],
  ["Robustez","T+32","B 86% · C 61%","watch"],
  ["Recomendação","T+35","ALT-B · decisão em 28 min","alert"],
  ["Decisão","T+36","DEC-0248 enviada à Torre","alert"],
  ["Aprovação","T+40","Gestor aprova ALT-B","ok"],
  ["Plano v19","T+41","PLN-2208-v19 publicado","ok"],
  ["Workflows","T+42","12 jobs · owners · SLA","info"],
  ["Desvio","T+50","Bomba MB-02 +18 min","watch"],
  ["Replan trigger","T+55","Chuva 73 → 91 mm · MATERIAL","critical"],
  ["Candidato v20","T+56","Nova versão preserva v19","alert"],
  ["Execução","T+70","Evento em curso","watch"],
  ["Realizado","T+90","Perda real 4,2 kt","info"],
  ["Recovery","T+120","8,2 kt preservadas","ok"],
].map(([label,time,note,tone]) => ({ label, time, note, tone: tone as Tone }));

export const planningBaseFeed = [
  { agent:"PLANNING ORCHESTRATOR", text:"Baseline PLN-2026-08-07-v18 carregado sem alterar sistemas oficiais.", type:"ok" as Tone },
  { agent:"CONSTRAINT GUARDIAN", text:"PlanningConstraintSet recebeu 4 restrições; 2 são hard constraints.", type:"watch" as Tone },
  { agent:"DECISION WINDOW", text:"Janela útil para mobilizar MB-02: 28 min.", type:"alert" as Tone },
  { agent:"ADHERENCE", text:"Plano vigente com 92,4% de aderência; 2 desvios monitorados.", type:"info" as Tone },
  { agent:"RECOMMENDATION", text:"ALT-B é a opção mais robusta em P10/P50/P90.", type:"ok" as Tone },
];

export const planningScenarioFeed: Record<number,{agent:string;text:string;type:Tone}> = {
  1:{agent:"EVENT BUS",text:"18:45:44 · chain.signal.created · CHS-0184 recebido.",type:"critical"},
  2:{agent:"PLANNING ORCHESTRATOR",text:"18:45:45 · baseline v18 carregado; SCN-0184 criado.",type:"info"},
  3:{agent:"SCENARIO GENERATOR",text:"18:45:47 · 6 alternativas geradas pelo Action Catalog.",type:"info"},
  4:{agent:"CONSTRAINT GUARDIAN",text:"18:45:49 · 2 alternativas inviáveis: C19 em manutenção e recurso tardio.",type:"watch"},
  6:{agent:"OPTIMIZATION",text:"18:45:52 · 4 alternativas posicionadas na fronteira de Pareto.",type:"info"},
  7:{agent:"ROBUST PLANNING",text:"ALT-B funciona em 17/20 variantes · robustness 86/100.",type:"ok"},
  8:{agent:"RESOURCE",text:"18:45:55 · MB-02 disponível, acessível e pronta em 47 min.",type:"ok"},
  9:{agent:"RECOMMENDATION",text:"18:46:02 · DEC-0248 enviada à Torre; prazo 28 min.",type:"alert"},
  10:{agent:"HUMAN DECISION",text:"ALT-B aprovada explicitamente pelo gestor.",type:"ok"},
  11:{agent:"WORKFLOW MANAGER",text:"PLN-2208-v19 publicado; plano versionado.",type:"ok"},
  12:{agent:"WORKFLOW MANAGER",text:"A02 → WF-UTIL-PUMP → JOB-3948 → Utilities.",type:"info"},
  13:{agent:"ADHERENCE",text:"Mobilização MB-02 atrasou 18 min; aderência 84%.",type:"watch"},
  14:{agent:"REPLANNING",text:"Mudança material: chuva P50 73 → 91 mm.",type:"critical"},
  15:{agent:"REPLANNING",text:"PLAN CANDIDATE v20 criado; v19 permanece vigente.",type:"alert"},
  17:{agent:"VERIFICATION",text:"Impacto real 4,2 kt versus 4,8 kt planejado.",type:"info"},
  18:{agent:"RECOVERY",text:"Ciclo concluído: 8,2 kt preservadas.",type:"ok"},
};

const alternatives = [
  {id:"BASE",name:"Sem intervenção",loss:"12,4 kt",cost:"R$ 0",risk:"ALTO",delay:"3h20",recovery:"9h30",robust:42,tone:"critical" as Tone,status:"BASELINE"},
  {id:"A",name:"Mitigação parcial",loss:"9,2 kt",cost:"R$ 25 mil",risk:"MODERADO",delay:"2h40",recovery:"6h00",robust:68,tone:"watch" as Tone,status:"FACTÍVEL"},
  {id:"B",name:"Mitigação robusta",loss:"4,8 kt",cost:"R$ 62 mil",risk:"BAIXO",delay:"1h05",recovery:"3h10",robust:86,tone:"ok" as Tone,status:"RECOMENDADA"},
  {id:"C",name:"Antecipação intensiva",loss:"2,9 kt",cost:"R$ 110 mil",risk:"MODERADO",delay:"0h00",recovery:"4h00",robust:61,tone:"alert" as Tone,status:"PARETO"},
];

const agents = [
  ["PLANNING ORCHESTRATOR","Monta o problema, escolhe motores e preserva ScenarioContext.","SCN-0184"],
  ["SCENARIO GENERATOR","Combina ações aprovadas e cria deltas contra baseline.","6 alternativas"],
  ["CONSTRAINT GUARDIAN","Valida safety, recursos, ambiente, contratos e tempo.","2 rejeitadas"],
  ["OPTIMIZATION","Executa MILP, rede, estoque e constraint programming.","4 factíveis"],
  ["RELAXATION ADVISOR","Explica inviabilidade sem relaxar safety ou ambiente.","1 sugestão"],
  ["RESOURCE","Verifica acesso, qualificação, deslocamento e setup.","MB-02 · 47 min"],
  ["MAINTENANCE","Busca janelas compatíveis com risco e redundância.","C17 · 08–11h"],
  ["LOGISTICS","Cruza trem, pátio, navio, vento e contrato.","MV Atlas · 18:30"],
  ["ENVIRONMENTAL","Impõe água, efluente, poeira, vento e áreas sensíveis.","HARD"],
  ["SAFETY","Veta opções inseguras sem compensação por produção.","GUARDRAIL"],
  ["RECOMMENDATION","Explica benefício, custo, risco, robustez e deadline.","ALT-B · 78%"],
  ["DECISION WINDOW","Calcula impacto − lead time − margem.","28 min"],
  ["ADHERENCE","Compara plano, jobs e realizado.","84%"],
  ["REPLANNING","Cria versão candidata em mudança material.","v20"],
];

function Pill({tone="info",children}:{tone?:Tone;children:ReactNode}) {
  return <span className={`planning-pill tone-${tone}`}><i />{children}</span>;
}
function Head({eyebrow,title,side}:{eyebrow:string;title:string;side?:ReactNode}) {
  return <div className="planning-head"><div><span>{eyebrow}</span><h2>{title}</h2></div>{side}</div>;
}
function StateLanes() {
  return <div className="planning-state-lanes">
    <article className="live"><header><span>LIVE STATE</span><Pill tone="critical">OBSERVADO</Pill></header><strong>C17 82% · D04-03 OFF</strong><small>SCADA / M4 · somente leitura</small></article>
    <article className="baseline"><header><span>BASELINE PLAN</span><Pill tone="info">v18</Pill></header><strong>Produção 100% · MV Atlas 21:00</strong><small>Manutenção C17 · 02:00</small></article>
    <article className="scenario"><header><span>SCENARIO STATE</span><Pill tone="ok">ALT-B</Pill></header><strong>C17 88% · MB-02 ON</strong><small>MV Atlas 18:30 · sandbox</small></article>
  </div>;
}
function DecisionClock() {
  return <div className="planning-decision-clock"><span>DECISION DEADLINE</span><strong>28:00</strong><small>impacto − lead time − margem</small><i><b style={{width:"58%"}} /></i></div>;
}

function Situation(props:Props) {
  const kpis:Array<[string,string,string,string,Tone]> = [
    ["Aderência",props.scenarioStep>=13?"84,0%":"92,4%",props.scenarioStep>=13?"−8,4 pp":"+1,2 pp","PLN-v19 · execução",props.scenarioStep>=13?"watch":"ok"],
    ["Produção em risco",props.scenarioStep>=8?"4,8 kt":"38,2 kt",props.scenarioStep>=8?"−7,6 kt":"P90 · 72h","C17 + chuva",props.scenarioStep>=8?"watch":"critical"],
    ["Restrições","4","2 críticas","asset · clima · porto","alert"],
    ["Janela de decisão","1h42","28 min p/ MB-02","ruptura 21:04","alert"],
    ["Melhor alternativa","Cenário B","+7,6 kt","robustness 86/100","ok"],
    ["Risco residual","BAIXO","confidence 78%","safety mantida","ok"],
  ];
  return <div className="planning-view"><StateLanes /><section className="planning-kpis">{kpis.map(([label,value,delta,note,tone])=><article className={`panel planning-kpi tone-${tone}`} key={label}><header><span>{label}</span><Pill tone={tone}>{delta}</Pill></header><strong>{value}</strong><small>{note}</small><div>{[28,36,44,51,63,58,72,68].map((v,i)=><i key={i} style={{height:`${v}%`}} />)}</div></article>)}</section>
    <section className="planning-situation-grid"><article className="panel planning-status-card"><Head eyebrow="PLAN STATUS · PLN-v18" title="Plano em risco · probabilidade 76%" side={<Pill tone="critical">AT RISK</Pill>} /><div className="planning-status-main"><div className="planning-risk-ring"><span><strong>76</strong><small>%</small></span></div><div><h3>C17 + chuva comprometem produção, estoque e navio</h3><p>Primeira ruptura em U3 às <b>21:04</b>. A mobilização precisa ser decidida antes de perder efetividade.</p><dl><div><dt>Causa</dt><dd>C17 · 46%</dd></div><div><dt>Contrato</dt><dd>C-2048</dd></div><div><dt>Recovery</dt><dd>9h30</dd></div></dl></div></div><DecisionClock /></article>
    <article className="panel planning-changes"><Head eyebrow="DESDE 18:30" title="O que mudou?" />{[["Produção","96%","88%"],["C17","96%","82%"],["MV Atlas","ON PLAN","AT RISK"],["Manutenção","compatível","conflito"],["Recovery","4h00","9h30"]].map(([name,before,after])=><div key={name}><strong>{name}</strong><span>{before}</span><b>→</b><span>{after}</span></div>)}<button onClick={()=>props.onToast("Lineage FR-2204 → CHS-0184 aberto")}>Ver cadeia causal →</button></article></section>
    <section className="planning-map-grid"><article className="panel planning-map-panel"><Head eyebrow="ARCGIS MAPS SDK · SCN-B" title="Restrições, recursos e ações" side={<Pill tone="ok">SYNC</Pill>} /><div className="planning-map-wrap">{props.renderMap()}<div className="planning-map-overlays"><button onClick={()=>props.onSelectAsset("CONV-C17")}>C17 · 82%</button><button>MB-02 · 2,8 km</button><button>V-08 · bloqueada</button><button>Berço 2 · vento</button></div><div className="planning-map-status"><i />{props.mapStatus}</div></div></article>
    <aside className="panel planning-recommendation"><Head eyebrow="RECOMMENDATION · DEC-0248" title="Aprovar Cenário B" side={<Pill tone="ok">78% CONF.</Pill>} /><p>Reduz <b>12,4 → 4,8 kt</b>, preserva C-2048, usa recursos disponíveis, mantém safety e custa menos que C.</p><dl><div><dt>Preservado</dt><dd>+7,6 kt</dd></div><div><dt>Atraso evitado</dt><dd>2h15</dd></div><div><dt>Custo</dt><dd>R$ 62 mil</dd></div><div><dt>Recovery</dt><dd>3h10</dd></div></dl><div className="planning-tradeoff"><b>Trade-off</b><span>C preserva +1,9 kt, custa +R$ 48 mil e eleva risco.</span></div><footer><button onClick={()=>props.onToast("DEC-0248 aprovada; PLN-v19 preparado")}>Aprovar</button><button onClick={()=>props.onToast("Matriz A/B/C aberta")}>Comparar</button><button onClick={()=>props.onToast("ALT-B em modo SCENARIO")}>Ajustar</button></footer></aside></section></div>;
}

function Plan72h(props:Props) {
  const rows=[["PRODUÇÃO","U1 · campanha A",2,24,"ok"],["","U2 · campanha B",10,31,"info"],["","U3 · C17 restrita",20,30,"critical"],["FERROVIA","T-481 · chegada",5,18,"ok"],["","T-482 · +54 min",32,17,"watch"],["PORTO","MV Atlas · antecipado",18,21,"ok"],["","Ocean Star · B1",49,24,"info"],["MANUTENÇÃO","C17 · 08–11h",57,14,"watch"]];
  return <div className="planning-view"><section className="planning-72-hero"><article className="panel"><div><span>RISK-INFORMED OPERATIONAL PLAN</span><h2>Plano Integrado 72H · v19</h2><p>Clima, capacidade, produção, manutenção, ferrovia, estoque, porto e recursos.</p></div><div>{["24H","72H","7D"].map(item=><button className={item==="72H"?"active":""} onClick={()=>props.onHorizon(item==="24H"?"+24H":item==="72H"?"+72H":"7D")} key={item}>{item}</button>)}</div></article><aside className="panel"><Head eyebrow="SHIFT PLAN" title="Turno B · 14–22h" side={<Pill tone="watch">ATENÇÃO</Pill>} /><dl><div><dt>Produção</dt><dd>94%</dd></div><div><dt>Ações</dt><dd>5</dd></div><div><dt>Manutenções adiadas</dt><dd>2</dd></div></dl><button onClick={props.onTower}>Passagem de turno</button></aside></section>
    <article className="panel planning-gantt"><Head eyebrow="GANTT · BASELINE × ALT-B" title="Agora → +72 horas" side={<Pill tone="critical">RAIN P90</Pill>} /><div className="planning-gantt-scale"><span>AGORA</span><span>+6H</span><span>+12H</span><span>+24H</span><span>+48H</span><span>+72H</span></div><div className="planning-weather-track"><strong>CHUVA</strong><i className="normal" style={{left:"0%",width:"16%"}} /><i className="severe" style={{left:"16%",width:"27%"}} /><i className="normal" style={{left:"43%",width:"57%"}} /><span>73 → 91 mm</span></div><div className="planning-capacity-track"><strong>C17</strong><i style={{left:"0%",width:"20%"}}>96%</i><i className="restricted" style={{left:"20%",width:"31%"}}>82 → 88%</i><i style={{left:"51%",width:"49%"}}>96%</i></div>{rows.map(([group,name,left,width,tone])=><div className="planning-gantt-row" key={name as string}><strong>{group}</strong><span>{name}</span><i className={`tone-${tone}`} style={{left:`${left}%`,width:`${width}%`}}>{name}</i></div>)}<footer><span><i className="baseline" />Baseline v18</span><span><i className="scenario" />ALT-B</span><small>ScenarioContext · {props.horizon}</small></footer></article>
    <section className="planning-72-grid"><article className="panel planning-week"><Head eyebrow="WEEKLY RISK-ADJUSTED" title="Semana 32 · fator climático" side={<Pill tone="info">SAZONAL ≠ HORÁRIO</Pill>} />{["Produção","Manutenção","Logística","Estoque","Água"].map((name,index)=><div key={name}><strong>{name}</strong>{["S","T","Q","Q","S","S","D"].map((day,i)=><i className={i===2||(i===3&&index<3)?"risk":""} key={`${day}-${i}`}>{day}</i>)}</div>)}<p>Calor acima do normal nas próximas 4 semanas ajusta recursos, estoque e água.</p></article><article className="panel planning-horizons"><Head eyebrow="HORIZONTES" title="Escalas de decisão" />{[["0–2h","Resposta"],["2–6h","Preparação"],["6–24h","Turnos"],["24–72h","Plano operacional"],["3–7d","Produção/logística"],["1–4w","Manutenção"],["1–6m","Sazonal"],["1–5a","CAPEX"]].map(([time,purpose])=><div key={time}><b>{time}</b><span>{purpose}</span></div>)}</article></section></div>;
}

function ScenarioFactory(props:Props) {
  const [step,setStep]=useState(1); const [created,setCreated]=useState(false);
  const submit=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(step<7)setStep(step+1);else{setCreated(true);props.onToast("SCN-0184 enviado à Simulation Engine");}};
  const steps=["Motivo","Horizonte","Baseline","Restrições","Premissas","Objetivos","Owner"];
  return <div className="planning-view"><StateLanes /><section className="planning-scenario-grid"><form className="panel planning-wizard" onSubmit={submit}><Head eyebrow="SCENARIO FACTORY" title={created?"SCN-0184 · READY":"Novo cenário"} side={<Pill tone={created?"ok":"info"}>{created?"READY":`ETAPA ${step}/7`}</Pill>} /><div className="planning-wizard-steps">{steps.map((item,index)=><button type="button" onClick={()=>setStep(index+1)} className={step===index+1?"active":step>index+1?"done":""} key={item}><i>{step>index+1?"✓":index+1}</i><span>{item}</span></button>)}</div><div className="planning-wizard-body">
    {step===1?<><label>Nome<input defaultValue="Chuva severa · C17 + porto" /></label><label>Trigger<select><option>ChainSignal CHS-0184</option><option>ClimateSignal</option><option>Manual</option></select></label><label>Motivo<select><option>Clima + restrição operacional</option><option>Manutenção</option><option>Logística</option></select></label></>:null}
    {step===2?<><label>Horizonte<select><option>72 horas</option><option>24 horas</option><option>7 dias</option></select></label><label>Início<input type="datetime-local" defaultValue="2026-08-07T18:45" /></label><label>Fim<input type="datetime-local" defaultValue="2026-08-10T18:45" /></label></>:null}
    {step===3?<><label className="wide">Baseline<select><option>PLN-2026-08-07-v18 · válido</option></select></label><div className="planning-baseline-lock"><span>🔒</span><p><b>Baseline imutável</b><small>Somente deltas; SCADA, EAM, lineup e contratos intactos.</small></p></div></>:null}
    {step===4?<div className="planning-auto-constraints">{[["C17","82%","HARD"],["D04-03","OFF","HARD"],["Berço 2","vento 22–01:30","HARD"],["Pátio Produto","4h32","SOFT"]].map(([name,value,kind])=><label key={name}><input type="checkbox" defaultChecked /><span><b>{name} · {value}</b><small>preenchimento automático</small></span><Pill tone={kind==="HARD"?"critical":"watch"}>{kind}</Pill></label>)}</div>:null}
    {step===5?<><label>Forecast<select><option>P50 · FR-2204</option><option>P90</option></select></label><label>Inventário<select><option>Estado reconciliado</option></select></label><label>Filas<select><option>ETA atual</option></select></label><label>Hora extra<select><option>Não permitida</option></select></label></>:null}
    {step===6?<div className="planning-objectives">{[["Safety","HARD",100],["Produção","MAX",30],["Contrato","MAX",30],["Custo","MIN",20],["Recovery","MIN",20],["Ambiente","HARD",100]].map(([name,mode,value])=><label key={name as string}><input type="checkbox" defaultChecked /><span><b>{name}</b><small>{mode}</small></span><input type="range" defaultValue={Number(value)} disabled={mode==="HARD"} /><strong>{mode==="HARD"?"NÃO NEGOCIÁVEL":`${value}%`}</strong></label>)}</div>:null}
    {step===7?<><label>Owner<select><option>Planejamento Integrado</option></select></label><label>Probabilidade<select><option>P50 + robustez P10/P90</option></select></label><label className="wide">Governança<textarea defaultValue="Aprovação obrigatória para publicar, mobilizar recursos ou alterar manutenção/navio." /></label></>:null}
    </div><footer><span>LIVE e BASELINE somente leitura</span><button type="button" disabled={step===1} onClick={()=>setStep(step-1)}>Voltar</button><button>{step===7?"Criar & executar":"Continuar"}</button></footer></form>
    <aside className="planning-scenario-side"><article className="panel"><Head eyebrow="SCENARIO CONTEXT" title="Linhagem" /><dl><div><dt>scenario</dt><dd>SCN-0184</dd></div><div><dt>baseline</dt><dd>PLN-v18</dd></div><div><dt>forecast</dt><dd>FR-2204</dd></div><div><dt>hazard</dt><dd>HMR-882</dd></div><div><dt>chain</dt><dd>CHS-0184</dd></div></dl></article><article className="panel planning-branching"><Head eyebrow="BRANCHING" title="Delta contra baseline" />{[["A","Limpeza"],["B","Bomba + estoque"],["B1","P50"],["B2","P90"],["C","Antecipação"]].map(([id,note],index)=><button style={{marginLeft:index===2||index===3?48:index?24:0}} key={id}><i /><span><b>SCN-0184-{id}</b><small>{note}</small></span></button>)}<p>D04-03 OFF → ON · apenas override persistido.</p></article></aside></section></div>;
}

function Alternatives(props:Props) {
  const [selected,setSelected]=useState("B"); const [view,setView]=useState("Matriz"); const [approved,setApproved]=useState(false);
  const chosen=alternatives.find(a=>a.id===selected)??alternatives[2];
  return <div className="planning-view"><section className="planning-decision-hero"><article className="panel"><div><span>DECISION REQUEST · DEC-0248</span><h2>Qual alternativa preserva melhor segurança e continuidade?</h2><p>Mesmo contexto e hard constraints. Segurança nunca é trocada por produção.</p></div><DecisionClock /></article><aside className="panel"><Pill tone={approved?"ok":"alert"}>{approved?"APPROVED":"HUMAN DECISION"}</Pill><strong>{approved?"PLN-v19":"28 min"}</strong><small>{approved?"versionado":"até expirar"}</small></aside></section>
    <section className="planning-alternative-cards">{alternatives.map(item=><button className={`panel tone-${item.tone} ${selected===item.id?"selected":""}`} onClick={()=>setSelected(item.id)} key={item.id}><header><span>ALT-{item.id}</span><Pill tone={item.tone}>{item.status}</Pill></header><h3>{item.name}</h3><p>{item.id==="B"?"Limpar D04, mobilizar MB-02, elevar estoque e reprogramar C17.":item.id==="C"?"Antecipar produção, estoque e navio; maior custo.":item.id==="A"?"Limpeza e resequenciamento sem bomba.":"Referência obrigatória."}</p><dl><div><dt>Perda</dt><dd>{item.loss}</dd></div><div><dt>Custo</dt><dd>{item.cost}</dd></div><div><dt>Risco</dt><dd>{item.risk}</dd></div><div><dt>Navio</dt><dd>{item.delay}</dd></div><div><dt>Recovery</dt><dd>{item.recovery}</dd></div><div><dt>Robustez</dt><dd>{item.robust}</dd></div></dl></button>)}</section>
    <section className="planning-compare-grid"><article className="panel planning-comparison"><Head eyebrow="COMPARAÇÃO" title={`ALT-${chosen.id} × baseline`} side={<div className="planning-view-switch">{["Matriz","Pareto","Robustez"].map(item=><button className={view===item?"active":""} onClick={()=>setView(item)} key={item}>{item}</button>)}</div>} />{view==="Matriz"?<table><thead><tr><th>Critério</th><th>BASE</th><th>A</th><th>B</th><th>C</th></tr></thead><tbody>{[["Produção perdida","12,4","9,2","4,8","2,9 kt"],["Custo","0","25","62","110 mil"],["Risco","Alto","Moderado","Baixo","Moderado"],["Atraso","3h20","2h40","1h05","0"],["Recovery","9h30","6h","3h10","4h"]].map(row=><tr key={row[0]}>{row.map((cell,index)=><td className={index===3?"recommended":""} key={`${row[0]}-${index}`}>{index===0?<b>{cell}</b>:cell}</td>)}</tr>)}</tbody></table>:view==="Pareto"?<div className="planning-pareto"><span className="axis-y">PRODUÇÃO ↑</span><span className="axis-x">CUSTO →</span>{alternatives.map((a,index)=><button style={{left:`${18+index*21}%`,bottom:`${22+[0,26,54,68][index]}%`}} key={a.id}><i>{a.id}</i><small>{a.cost}<br />{a.loss}</small></button>)}<small>Fronteira de Pareto · trade-offs visíveis</small></div>:<div className="planning-robust"><section>{[["P10","BOA","ÓTIMA"],["P50","BOA","ÓTIMA"],["P90","ACEITÁVEL","FALHA"]].map(row=><div key={row[0]}><b>{row[0]}</b><span>B · {row[1]}</span><span className={row[2]==="FALHA"?"critical":""}>C · {row[2]}</span></div>)}</section><aside><div className="planning-robust-ring"><span><b>86</b><small>/100</small></span></div><h3>B é mais robusta</h3><p>17/20 variantes.</p></aside></div>}</article>
    <aside className="panel planning-decision-form"><Head eyebrow="APROVAÇÃO" title={`ALT-${chosen.id}`} /><dl><div><dt>Perda</dt><dd>{chosen.loss}</dd></div><div><dt>Custo</dt><dd>{chosen.cost}</dd></div><div><dt>Robustez</dt><dd>{chosen.robust}/100</dd></div></dl><label>Responsável<select><option>Gerência de Operações · N2</option></select></label><label>Justificativa<textarea defaultValue="Menor risco residual, recursos disponíveis e contrato preservado." /></label><label className="planning-approval-check"><input type="checkbox" defaultChecked /><span>Safety, ambiente e recursos revisados.</span></label><footer><button disabled={approved||chosen.id==="BASE"} onClick={()=>{setApproved(true);props.onToast("ALT-B aprovada; PLN-v19 criado");}}>{approved?"Aprovado ✓":"Aprovar & publicar"}</button><button>Rejeitar</button></footer></aside></section>
    <article className="panel planning-infeasible"><Head eyebrow="FEASIBILITY VISÍVEL" title="2 alternativas eliminadas" side={<Pill tone="critical">NOT FEASIBLE</Pill>} /><div><span><b>ALT-D</b><strong>Usar C19</strong><small>Em manutenção oficial</small></span><span><b>ALT-E</b><strong>Bomba externa</strong><small>Chega 3h20; impacto 1h42</small></span></div><p>Relaxation Advisor explica, mas não relaxa safety ou ambiente.</p></article></div>;
}

function Optimization(props:Props) {
  const [mode,setMode]=useState("Básico"); const [running,setRunning]=useState(false);
  const run=()=>{setRunning(true);window.setTimeout(()=>{setRunning(false);props.onToast("OPT-882 concluída · ALT-B recomendada");},900);};
  return <div className="planning-view"><section className="planning-optimizer-hero"><article className="panel"><div><span>MULTI-OBJECTIVE OPTIMIZATION</span><h2>IA interpreta · solver resolve · IA explica</h2><p>Rede, estoque, MILP, constraint programming, heurísticas e simulação.</p></div><div className="planning-engine-flow">{["SIGNAL","CONSTRAINTS","GENERATE","SIMULATE","FEASIBILITY","OPTIMIZE","EXPLAIN"].map((item,index)=><span key={item}><i>{index+1}</i>{item}{index<6?<b>→</b>:null}</span>)}</div></article><aside className="panel"><Head eyebrow="OPTIMIZATION RUN" title="OPT-882" side={<Pill tone={running?"watch":"ok"}>{running?"RUNNING":"COMPLETED"}</Pill>} /><dl><div><dt>Runtime</dt><dd>3,8 s</dd></div><div><dt>Gap</dt><dd>0,8%</dd></div><div><dt>Solver</dt><dd>MILP + CP</dd></div></dl></aside></section>
    <section className="planning-optimizer-grid"><form className="panel planning-optimizer-form" onSubmit={e=>{e.preventDefault();run();}}><Head eyebrow="CONFIGURAÇÃO" title="PP-0184" side={<div className="planning-view-switch">{["Básico","Avançado"].map(item=><button type="button" className={mode===item?"active":""} onClick={()=>setMode(item)} key={item}>{item}</button>)}</div>} /><div className="planning-optimizer-objectives"><div className="planning-hard-objective"><span><b>Safety</b><small>restrição rígida</small></span><strong>HARD</strong></div>{[["Produção",30],["Contrato",30],["Custo",20],["Recovery",20]].map(([name,value])=><label key={name as string}><span><b>{name}</b><small>objetivo</small></span><input type="range" defaultValue={Number(value)} /><strong>{value}%</strong></label>)}</div>{mode==="Avançado"?<div className="planning-advanced"><label>Solver<select><option>Hybrid MILP + CP</option></select></label><label>Gap<input defaultValue="1,0%" /></label><label>Time limit<input defaultValue="60 s" /></label><label>Seed<input defaultValue="2417" /></label></div>:<div className="planning-basic-summary"><span>Objetivo</span><b>Plano factível e robusto ao menor custo/risco</b><small>Safety e ambiente não são compensáveis.</small></div>}<footer><span>126 constraints</span><button disabled={running}>{running?"Otimizando…":"Executar otimização"}</button></footer></form>
    <article className="panel planning-sensitivity"><Head eyebrow="TORNADO" title="Sensibilidade" />{[["C17 capacity",36],["Rain intensity",28],["Inventory",18],["Port weather",11],["Train ETA",7]].map(([name,value])=><div key={name as string}><b>{name}</b><i><span style={{width:`${Number(value)*2.4}%`}} /></i><strong>{value}%</strong></div>)}</article></section>
    <section className="planning-optimizer-results"><article className="panel"><Head eyebrow="DECISION MATRIX" title="Score explicável" /><table><thead><tr><th>Alt.</th><th>Safety</th><th>Produção</th><th>Custo</th><th>Ambiente</th><th>Contrato</th><th>Robustez</th></tr></thead><tbody>{[["A","PASS",62,81,"PASS",68,68],["B","PASS",86,72,"PASS",94,86],["C","PASS",94,48,"PASS",98,61]].map(row=><tr className={row[0]==="B"?"recommended":""} key={row[0] as string}>{row.map(cell=><td key={String(cell)}>{cell}</td>)}</tr>)}</tbody></table></article><aside className="panel planning-fallback"><Head eyebrow="DEGRADED MODE" title="Continuidade" /><p>Optimizer offline: heurísticas aprovadas. M5 offline: último estado válido.</p><b>Rule-Based Planning</b><small>Confidence 78 → 59%</small></aside></section></div>;
}

const domainData:Record<string,{title:string;eyebrow:string;cards:string[][];rows:string[][]}> = {
  "Produção & Estoques":{title:"Production Plan · preposicionamento",eyebrow:"PRODUÇÃO + MATERIAL GRADE",cards:[["Produção preservada","+7,6 kt","ok"],["Sequência","A → C → B","info"],["Pátio Minério","510 kt","watch"],["C-2048","PRESERVADO","ok"]],rows:[["Pellet A","188 kt","U1 · U3","READY"],["Pellet B","122 kt","U2","BUFFER"],["Sinter feed","84 kt","U3","HOLD"]]},
  "Logística & Porto":{title:"Rail & Port Plan · trem ao navio",eyebrow:"CARGO READINESS + WEATHER WINDOW",cards:[["T-482","+54 min","watch"],["MV Atlas","18:30","ok"],["Berço 2","21–01 restrito","critical"],["Contrato","PRESERVADO","ok"]],rows:[["T-481","16:10","Pátio Minério","ON TIME"],["T-482","22:04","Pátio Minério","+54 min"],["MV Atlas","18:30","Berço 2","ALT-B"]]},
  "Manutenção & Recursos":{title:"Maintenance Window + Resource Plan",eyebrow:"C17 · MB-02 · ROUTING",cards:[["C17 baseline","02–05h","critical"],["C17 alternativa","08–11h","ok"],["MB-02","47 min ready","ok"],["Conflitos","1 material","watch"]],rows:[["MB-02","2,8 km","32 + 15 min","FEASIBLE"],["Equipe elétrica","4,1 km","41 + 12 min","AVAILABLE"],["GEN-01","6,5 km","54 + 20 min","AVAILABLE"]]},
  "Ambiental & Adaptação":{title:"Environmental Constraints + Adaptation",eyebrow:"HARD LIMITS + PORTFÓLIO",cards:[["Reservatório","68 → 54%","watch"],["Drenagem","+2,1 m³/s","ok"],["Flood P90","0,51 → 0,31 m","ok"],["Portfólio","4 opções","info"]],rows:[["Sem CAPEX","86 h downtime","42/100","BASE"],["Bomba extra","54 h downtime","71/100","OPTION"],["Drenagem ampliada","31 h downtime","84/100","PREFERRED"]]},
};
function DomainScreen(props:Props) {
  const data=domainData[props.subview]; const [target,setTarget]=useState(510);
  return <div className="planning-view"><section className="planning-domain-hero panel"><div><span>{data.eyebrow}</span><h2>{data.title}</h2><p>Plano operacional governado, temporal e sincronizado ao território.</p></div><Pill tone="info">SCENARIO B</Pill></section><section className="planning-domain-kpis">{data.cards.map(([label,value,tone])=><article className={`panel tone-${tone}`} key={label}><span>{label}</span><b>{value}</b><small>PLN-v19</small></article>)}</section>
    <section className="planning-domain-grid"><article className="panel planning-domain-main"><Head eyebrow={data.eyebrow} title="Plano comparável · baseline × cenário" />{props.subview==="Produção & Estoques"?<><div className="planning-sequence"><span><b>BASELINE</b>A → B → C</span><i>→</i><span className="scenario"><b>ALT-B</b>A → C → B</span></div><div className="planning-stock-chart"><span className="safety">SAFETY 360 kt</span><span className="target" style={{bottom:`${target/7}%`}}>TARGET {target} kt</span>{[420,448,470,510,502,474,451].map((v,i)=><i style={{left:`${i*15}%`,bottom:`${v/7}%`}} key={i} />)}</div><label className="planning-range">Buffer target<input type="range" min="420" max="560" step="10" value={target} onChange={e=>setTarget(Number(e.target.value))} /><b>{target} kt</b></label></>:props.subview==="Logística & Porto"?<><div className="planning-weather-window"><span className="open" style={{left:"0",width:"28%"}}>18–21 OPEN</span><span className="closed" style={{left:"28%",width:"36%"}}>21–01 RESTRIÇÃO</span><span className="open" style={{left:"64%",width:"36%"}}>01–06 OPEN</span><i className="baseline" style={{left:"41%"}}>BASE 22:00</i><i className="scenario" style={{left:"7%"}}>ALT-B 18:30</i></div><p>ArcGIS fornece localização, bloqueios e rotas; o scheduler portuário permanece responsável.</p></>:props.subview==="Manutenção & Recursos"?<><div className="planning-maint-track"><span>00</span><span>03</span><span>06</span><span>09</span><span>12</span><i className="rain">CHUVA 01–06</i><i className="baseline">BASE 02–05</i><i className="scenario">ALT-B 08–11</i></div><div className="planning-map-wrap">{props.renderMap()}<div className="planning-map-overlays"><button>MB-02 · 2,8 km</button><button>V-08 · bloqueada</button></div></div></>:<><div className="planning-hard-list">{[["Água","≤84%","PASS"],["Efluente","≤7,8 m³/s","PASS"],["Poeira","vento <45","WATCH"],["Área sensível","V-08 vedada","HARD"]].map(row=><span key={row[0]}><b>{row[0]}</b><small>{row[1]}</small><Pill tone={row[2]==="HARD"?"critical":row[2]==="WATCH"?"watch":"ok"}>{row[2]}</Pill></span>)}</div><button onClick={props.onHazards}>Rerun físico M3</button><button onClick={props.onRisk}>Valorar adaptação M7</button></>}</article>
    <aside className="panel planning-domain-table"><Head eyebrow="PLANNING OBJECTS" title="Detalhamento" />{data.rows.map(row=><div key={row[0]}><span>{row[0].slice(0,2)}</span><p><b>{row[0]}</b><small>{row[1]} · {row[2]}</small></p><Pill tone={row[3]==="FEASIBLE"||row[3]==="READY"||row[3]==="PREFERRED"||row[3]==="ALT-B"?"ok":"info"}>{row[3]}</Pill></div>)}<p className="planning-guardrail">Recomendação → aprovação → workflow → sistema responsável. Nenhum EAM, MES, TOS ou recurso é alterado autonomamente.</p></aside></section></div>;
}

function ApprovedPlan(props:Props) {
  const [approved,setApproved]=useState(false);
  const actions=[["A01","Limpar D04","17:00–17:30","Utilidades","READY","—"],["A02","Mobilizar MB-02","17:05–17:45","Utilidades","READY","A01"],["A03","Elevar estoque 510 kt","17:00–19:00","Produção","RUNNING","—"],["A04","Antecipar MV Atlas","18:20","Porto","PENDING","A03"],["A05","Inspecionar drenagem","17:50–18:20","HSE","PENDING","A02"]];
  return <div className="planning-view"><section className="planning-approved-hero"><article className={`panel ${approved?"approved":""}`}><div><span>APPROVED PLAN</span><h2>PLN-2208-v19</h2><p>ALT-B · válido 18:50–06:00 · baseline v18</p></div><div className="planning-plan-seal"><span>{approved?"✓":"…"}</span><b>{approved?"APPROVED":"UNDER REVIEW"}</b><small>aprovação humana</small></div><dl><div><dt>Preservado</dt><dd>7,6 kt</dd></div><div><dt>Custo</dt><dd>R$ 62 mil</dd></div><div><dt>Risco</dt><dd>BAIXO</dd></div><div><dt>Robustez</dt><dd>86/100</dd></div></dl><footer><button disabled={approved} onClick={()=>{setApproved(true);props.onToast("PLN-v19 aprovado; 12 jobs criados");}}>{approved?"Publicado ✓":"Aprovar plano"}</button><button>Solicitar ajuste</button></footer></article><aside className="panel"><Head eyebrow="WORKFLOW SUMMARY" title={approved?"12 jobs":"0 jobs"} /><b>{approved?"8 concluídos · 3 em curso · 1 atrasado":"Aguardando publicação"}</b><button onClick={props.onTower}>Central de Trabalho</button></aside></section>
    <article className="panel planning-action-table"><Head eyebrow="PLAN ACTIONS" title="Owners, prazos e dependências" side={<Pill tone="info">A01 → A02 → A05</Pill>} /><table><thead><tr><th>ID</th><th>Ação</th><th>Janela</th><th>Owner</th><th>Status</th><th>Depende</th><th>Workflow</th></tr></thead><tbody>{actions.map(([id,action,window,owner,status,dep])=><tr key={id}><td><b>{id}</b></td><td>{action}</td><td>{window}</td><td>{owner}</td><td><Pill tone={status==="READY"?"ok":status==="RUNNING"?"watch":"info"}>{approved&&id==="A02"?"DISPATCHED":status}</Pill></td><td>{dep}</td><td>{approved?(id==="A02"?"JOB-3948":`JOB-${3947+Number(id.slice(1))}`):"—"}</td></tr>)}</tbody></table></article>
    <section className="planning-workflow-grid"><article className="panel planning-workflow"><Head eyebrow="WORKFLOW MANAGER" title="Plano → execução" /><div>{[["A02","Action"],["WF-UTIL-PUMP","Workflow"],["JOB-3948","Job"],["Utilities","Owner"],["DISPATCHED","State"]].map(([id,type],i)=><span key={id}><i>{i+1}</i><b>{id}</b><small>{type}</small>{i<4?<strong>→</strong>:null}</span>)}</div><p>PLANNED → DISPATCHED → ACCEPTED → IN PROGRESS → COMPLETED / FAILED.</p></article><article className="panel planning-action-catalog"><Head eyebrow="ACTION CATALOG" title="Bomba móvel" /><dl><div><dt>Lead</dt><dd>45 min</dd></div><div><dt>Recursos</dt><dd>1 bomba · 2 operadores</dd></div><div><dt>Benefício</dt><dd>+2,1 m³/s</dd></div><div><dt>Custo</dt><dd>R$ 18 mil</dd></div><div><dt>Workflow</dt><dd>WF-UTIL-04</dd></div></dl><p>Agentes selecionam ações governadas; não inventam procedimentos.</p></article></section></div>;
}

function Adherence(props:Props) {
  const [candidate,setCandidate]=useState(false); const [rain,setRain]=useState(91);
  return <div className="planning-view"><section className="planning-adherence-hero"><article className="panel"><div><span>PLAN ADHERENCE · v19</span><h2>84% · um desvio material</h2><p>Plano ideal, jobs e realizado comparados continuamente.</p></div><div className="planning-adherence-ring"><span><b>84</b><small>%</small></span></div><dl><div><dt>Ações</dt><dd>12 · 8 concluídas</dd></div><div><dt>Atrasadas</dt><dd>2</dd></div><div><dt>Produção</dt><dd>96%</dd></div><div><dt>Risco residual</dt><dd>+12%</dd></div></dl></article><aside className="panel planning-replan-status"><Head eyebrow="REPLAN AGENT" title={candidate?"v20 · CANDIDATE":"Mudança material"} /><label>Chuva<input type="range" min="73" max="104" value={rain} onChange={e=>setRain(Number(e.target.value))} /><b>{rain} mm</b></label><p>{rain<=78?"Imaterial; v19 permanece.":"Mudança material; recalcular."}</p><button disabled={rain<=78||candidate} onClick={()=>{setCandidate(true);props.onToast("v20 candidato; v19 segue oficial");}}>{candidate?"Criado ✓":"Criar candidato v20"}</button></aside></section>
    <section className="planning-deviation-grid"><article className="panel planning-deviations"><Head eyebrow="DEVIATIONS" title="Execução × plano" />{[["DEV-041","MB-02","+18 min","MATERIAL"],["DEV-042","Estoque","−12 kt","MATERIAL"],["DEV-043","ETA T-482","+5 min","IMATERIAL"],["DEV-044","Chuva","73 → 91 mm","MATERIAL"],["DEV-045","Inspeção","no prazo","OK"]].map(([id,item,delta,status])=><div key={id}><span>{id}</span><b>{item}</b><strong>{delta}</strong><Pill tone={status==="MATERIAL"?"critical":status==="OK"?"ok":"info"}>{status}</Pill></div>)}</article><article className="panel planning-adherence-chart"><Head eyebrow="IDEAL × EXECUTED" title="Aderência por dimensão" />{[["Ações",92],["Tempo",74],["Produção",96],["Estoque",88],["Logística",81],["Safety",100]].map(([name,value])=><div key={name as string}><b>{name}</b><i><span style={{width:`${value}%`}} /></i><strong>{value}%</strong></div>)}</article></section>
    <section className="planning-version-delta"><article className="panel"><Head eyebrow="VERSIONING" title="v18 → v19 → v20" /><div className="planning-version-flow"><span><b>v18</b><small>SUPERSEDED</small></span><i>→</i><span className="current"><b>v19</b><small>APPROVED</small></span><i>→</i><span className={candidate?"candidate":"locked"}><b>v20</b><small>{candidate?"CANDIDATE":"NOT CREATED"}</small></span></div></article><article className="panel planning-delta-table"><Head eyebrow="DELTA v19 → v20" title="Mudanças" /><table><tbody>{[["MV Atlas","18:30","20:10"],["C17 maint.","08:00","10:00"],["Estoque","510","540 kt"]].map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={cell}>{i===0?<b>{cell}</b>:cell}</td>)}</tr>)}</tbody></table></article></section></div>;
}

function History(props:Props) {
  const [replay,setReplay]=useState(7);
  return <div className="planning-view"><section className="planning-history-grid"><aside className="panel planning-version-list"><Head eyebrow="PLAN HISTORY" title="Versões" />{[["v20","CANDIDATE","info"],["v19","APPROVED","ok"],["v18","SUPERSEDED","watch"],["v17","ARCHIVED","info"]].map(([id,status,tone])=><button key={id}><span><b>PLN-2208-{id}</b><small>07 AGO</small></span><Pill tone={tone as Tone}>{status}</Pill></button>)}</aside><article className="panel planning-lineage"><Head eyebrow="AUDITABLE LINEAGE" title="Forecast → job" /> <div>{[["FR-2204","Climate"],["HMR-882","Hazard"],["AI-2084","Asset"],["CHS-0184","Chain"],["SCN-0184","Scenario"],["ALT-B","Alternative"],["DEC-0248","Decision"],["PLN-v19","Plan"],["JOB-3948","Execution"]].map(([id,type],i)=><button onClick={i===0?props.onClimate:i===1?props.onHazards:i===2?props.onTwin:i===3?props.onChain:i===6?props.onTower:undefined} key={id}><i>{i+1}</i><b>{id}</b><small>{type}</small>{i<8?<strong>→</strong>:null}</button>)}</div></article></section>
    <article className="panel planning-replay"><Head eyebrow="EVENT REPLAY" title="Planejar, executar, medir e replanejar" /><div>{[[0,"Baseline"],[12,"Signal"],[25,"Scenario"],[37,"Optimize"],[50,"Decision"],[62,"Plan"],[75,"Execute"],[87,"Replan"],[100,"Recovery"]].map(([pos,label],i)=><span style={{left:`${pos}%`}} className={replay>=i?"active":""} key={label as string}><i>{replay>i?"✓":i+1}</i><b>{label}</b></span>)}</div><input type="range" min="0" max="8" value={replay} onChange={e=>setReplay(Number(e.target.value))} /></article>
    <section className="planning-outcome-grid"><article className="panel"><Head eyebrow="EXPECTED × ACTUAL" title="Resultado" />{[["Perda baseline","12,4 kt"],["Plano","4,8 kt"],["Realizado","4,2 kt"],["Preservado","8,2 kt"]].map(([label,value])=><div key={label}><span>{label}</span><b>{value}</b></div>)}<p>FORECAST → MODEL → ASSET → CHAIN → PLAN → EXECUTE → MEASURE</p></article><article className="panel"><Head eyebrow="OVERRIDES" title="Delta persistido" /><table><tbody>{[["D04-03","OFF","ON"],["C17","82%","88%"],["MV Atlas","21:00","18:30"],["Pátio","420","510 kt"]].map(row=><tr key={row[0]}>{row.map((cell,i)=><td key={cell}>{i===0?<b>{cell}</b>:cell}</td>)}</tr>)}</tbody></table></article></section></div>;
}

function AgentsIntegrations(props:Props) {
  const [section,setSection]=useState("Agentes");
  return <div className="planning-view"><div className="planning-section-switch">{["Agentes","Integrações","Event Bus","Agentic UI"].map(item=><button className={section===item?"active":""} onClick={()=>setSection(item)} key={item}>{item}</button>)}</div>
    {section==="Agentes"?<><article className="panel planning-agent-hero"><div><span>AGENTIC PLANNING</span><h2>14 agentes · decisão governada</h2><p>Análise automática; publicação e execução material com aprovação.</p></div><div>{["SIGNAL","SCENARIO","CHECK","SOLVER","RECOMMEND","APPROVE","EXECUTE","REPLAN"].map((item,i)=><span key={item}><i>{i+1}</i>{item}{i<7?<b>→</b>:null}</span>)}</div></article><section className="planning-agent-grid">{agents.map(([name,role,status],i)=><article className="panel" key={name}><header><span>AI</span><div><small>AGENT {String(i+1).padStart(2,"0")}</small><h3>{name}</h3></div><Pill tone={i===2||i===9?"critical":i>10?"watch":"ok"}>ACTIVE</Pill></header><p>{role}</p><dl><div><dt>Agora</dt><dd>{status}</dd></div><div><dt>Guardrail</dt><dd>sem escrita autônoma</dd></div></dl><footer><button onClick={()=>props.onToast(`${name}: evidências abertas`)}>Evidências</button><button>Pausar</button></footer></article>)}</section><article className="panel planning-agent-feed"><Head eyebrow="REAL-TIME FEED" title="SCN-0184" />{[["18:45:44","PO","CHS recebido"],["18:45:45","PO","baseline v18"],["18:45:47","SG","6 alternativas"],["18:45:49","CG","2 inviáveis"],["18:45:52","OP","4 otimizadas"],["18:45:55","RS","MB-02 disponível"],["18:45:58","RE","ALT-B recomendada"],["18:46:02","PO","DEC → Torre"]].map((row,i)=><div className={i===7?"current":"done"} key={row[0]}><time>{row[0]}</time><i>{i<7?"✓":"●"}</i><b>{row[1]}</b><strong>{row[2]}</strong></div>)}</article></>:null}
    {section==="Integrações"?<><section className="planning-integration-grid">{[[["M2 · Clima","ForecastProbability","FR-2204"],["M3 · Perigos","HazardSurface","HMR-882"],["M4 · Gêmeo","Asset State","AI-2084"],["M5 · Cadeia","PlanningConstraintSet","CHS-0184"]],[["M1 · Torre","Recommendation","DEC-0248"],["M3 · Perigos","Physical rerun","SCN-B"],["M4 · Gêmeo","Asset override","MB-02 ON"],["M5 · Cadeia","ChainScenario","ALT-B"],["M7 · Riscos","Cost + risk","7,6 kt"]]].map((group,gi)=><article className="panel" key={gi}><Head eyebrow={gi?"OUTPUT CONTRACTS":"INPUT CONTRACTS"} title={gi?"M6 → execução":"Módulos → M6"} />{group.map(row=><button key={row[0]}><span>{row[0].slice(0,2)}</span><p><b>{row[0]}</b><small>{row[1]}</small></p><strong>{row[2]}</strong></button>)}</article>)}</section><article className="panel planning-arcgis"><div><span>ARCGIS MAPS SDK 5.1</span><h2>Mapa, tempo, recursos, rotas e Living Atlas</h2><p>Map · Time Slider · Swipe · FeatureLayer · RouteLayer · Charts. Gantt próprio.</p></div><div><b>Living Atlas</b><span>VIIRS</span><span>Sentinel-2</span><span>Terrain 3D</span></div></article></>:null}
    {section==="Event Bus"?<section className="planning-event-grid"><article className="panel planning-event-bus"><Head eyebrow="EVENT BUS" title="Entradas e saídas" /><section><div><h3>ENTRADAS</h3>{["climate.signal.created","hazard.signal.created","asset.capacity.changed","chain.signal.created","plan.deviation"].map(e=><span key={e}>{e}</span>)}</div><div><h3>SAÍDAS</h3>{["planning.scenario.created","planning.alternative.infeasible","planning.optimization.completed","planning.recommendation.created","planning.plan.approved","planning.replan.requested"].map(e=><span key={e}>{e}</span>)}</div></section></article><article className="panel planning-payload"><Head eyebrow="PAYLOAD" title="recommendation.created" /><pre>{JSON.stringify({scenarioId:"SCN-0184",recommendedAlternative:"ALT-B",productionPreservedTons:7600,residualRisk:"low",confidence:.78},null,2)}</pre><button onClick={props.onTower}>Abrir na Torre</button></article></section>:null}
    {section==="Agentic UI"?<section className="planning-agentic-ui"><article className="panel planning-assistant"><Head eyebrow="PLANNING ASSISTANT" title="Pergunte ao cenário" /><div className="user-question">Se C17 ficar em 90%, atraso o navio?</div><div className="assistant-answer"><span>AI</span><p><b>Risco 12,4 → 3,1 kt</b><b>MV Atlas sem atraso material</b><b>Recovery 9h30 → 2h45</b><small>Delta criado e M5 recalculado.</small></p></div><button onClick={()=>props.onToast("SCN-B1 aberto")}>Abrir cenário</button><div className="user-question secondary">E se chover no P90?</div><div className="assistant-answer compact"><span>AI</span><p>Solicitarei rerun físico M3 antes de recalcular M4–M6.</p></div></article><aside className="panel planning-agent-actions"><Head eyebrow="AGENT ACTIONS" title="Rastreabilidade" />{[["create_scenario","SCN-B1","DONE"],["override_capacity","C17 90%","DONE"],["chain_recalculate","PR-884","DONE"],["physical_rerun","P90","APPROVAL"]].map(row=><div key={row[0]}><b>{row[0]}</b><small>{row[1]}</small><Pill tone={row[2]==="DONE"?"ok":"watch"}>{row[2]}</Pill></div>)}</aside></section>:null}</div>;
}

function Reports(props:Props) {
  const reports=["72h Operational Plan","Weekly Risk-Adjusted Plan","Scenario Comparison Report","Optimization Report","Resource Plan","Maintenance Risk Plan","Logistics Plan","Environmental Constraint Report","Plan Adherence Report","Replanning Report","Adaptation Options Report"];
  const [report,setReport]=useState(reports[0]);
  return <div className="planning-view"><section className="planning-reports-grid"><aside className="panel"><Head eyebrow="REPORT CATALOG" title="Entregáveis M6" />{reports.map((item,i)=><button className={report===item?"active":""} onClick={()=>setReport(item)} key={item}><span>{i<2?"LIVE":"PDF"}</span><b>{item}</b><strong>›</strong></button>)}</aside><article className="panel planning-report-preview"><header><div><span>ATLAS CLIMA · PLANEJAMENTO</span><h2>{report}</h2><p>07 AGO · SCN-0184 · PLN-v19</p></div><Pill tone="ok">VERSIONADO</Pill></header><section>{[["Plan status","AT RISK"],["Produção","7,6 kt"],["Risco","BAIXO"],["Decisão","28 min"],["Execução","84%"],["Recovery","3h10"]].map(row=><div key={row[0]}><span>{row[0]}</span><b>{row[1]}</b></div>)}</section><div className="planning-report-bars">{[["BASE",12.4],["A",9.2],["B",4.8],["C",2.9]].map(row=><span key={row[0] as string}><i style={{height:`${Number(row[1])*6}%`}} /><b>{row[1]} kt</b><small>{row[0]}</small></span>)}</div><footer><span>M2 · M3 · M4 · M5 · MES · EAM · ArcGIS</span><button onClick={()=>props.onToast(`${report} gerado`)}>Gerar pack</button></footer></article></section><article className="panel planning-report-structure"><Head eyebrow="SCENARIO COMPARISON" title="Estrutura auditável" />{["Trigger","Baseline","Constraints","Objectives","Alternatives","Results","Trade-offs","Sensitivity","Robustness","Recommendation","Residual risk","Decision"].map((item,i)=><span key={item}><i>{i+1}</i><b>{item}</b></span>)}</article></div>;
}

export function PlanningModule(props:Props) {
  return useMemo(()=>{
    if(props.subview==="Plano Integrado 72H") return <Plan72h {...props} />;
    if(props.subview==="Cenários") return <ScenarioFactory {...props} />;
    if(props.subview==="Alternativas & Decisão") return <Alternatives {...props} />;
    if(props.subview==="Otimização") return <Optimization {...props} />;
    if(domainData[props.subview]) return <DomainScreen {...props} />;
    if(props.subview==="Plano Aprovado") return <ApprovedPlan {...props} />;
    if(props.subview==="Aderência & Replan") return <Adherence {...props} />;
    if(props.subview==="Histórico & Versões") return <History {...props} />;
    if(props.subview==="Agentes & Integrações") return <AgentsIntegrations {...props} />;
    if(props.subview==="Relatórios") return <Reports {...props} />;
    return <Situation {...props} />;
  },[props]);
}
